config/routes.rb
Rails.application.routes.draw do

  # get 'homes/index'

  get "log_in" => "sessions#new", :as => "log_in"

  get "sign_up" => "users#new", :as => "sign_up"
  root :to => "homes#index"
  resources :users
  resources :sessions
  resources :people do
    resources :hobbies
  end
  resources :addresses

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :person
end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :user
  has_one :address, dependent: :destroy
  has_many :hobbies, dependent: :destroy

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def self.search(search)
	  if search
	  	where("gender LIKE ?" , "#{search}")
	  end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user #&& user.password_hash == BCrypt::Engine.hash_secret (password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def index
  	@addresses = Address.all
  end

  def new
   
    @person = Person.find(params[:person_id])
  	@address = Address.new
  end

  def create

    @person = Person.find(params[:address][:person_id])
  	@person.address = Address.new(address_params)
  	if @person.save
  		redirect_to address_path(@person.address)
  	else
  		render :new
  	end
  end

  def edit
  	@address = Address.find(params[:id])
  end

  def update
  	@address = Address.find(params[:id])
  	if @address.update(address_params)
  		redirect_to address_path(@address)
  	else
  		render :edit
  	end
  end

  def show
  	@address = Address.find(params[:id])
  end

  private

  	def address_params
  		params.require(:address).permit(:city, :state, :zip, :street, :person_id)
  		
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
before_action :person
before_action :hobby, only: [:show, :edit, :update, :destroy]

  def index
  	@hobbies = @person.hobbies
  end

  def new
  	@hobby = Hobby.new
  end

  def create
  	@hobby = @person.hobbies.new(hobby_params)
  	if @hobby.save
  		flash[:success] = '#{@hobby.name} has been created!'
  		redirect_to person_hobby_path(@person, @hobby)
  	else
  		render :new
  	end
  end

  def show
  end

  def edit
  end

  def update
  	if @hobby.update(hobby_params)
  		flash[:success] = "hobby has been updated!"
  		redirect_to person_hobby_path(@person, @hobby)
  	else
  		render :edit
  	end
  end


  def destroy
  	@hobby.destroy
  	redirect_to person_hobbies_path(@person)
  end

  private

  	def hobby_params
  		params.require(:hobby).permit(:description)
  	end

  	def hobby
  		@hobby = @person.hobbies.find(params[:id])
  	end

  	def person
  	
  		@person = Person.find(params[:person_id])
  	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @user_id = current_user.id
    @people = Person.all#.where("id != ?", current_user.id)
    @people - [@user_id]
    if params[:search]
      @people = Person.search(params[:search])
    else
    	@people = Person.all
    end
    
  end

  def show
  	@person = Person.find(params[:id])
    @user = current_user
    @person.address
  end

  def new

    @user = current_user.id
  	@person = Person.new 
  end

  def create
    @user_id = current_user.id
    @person = Person.new(person_params)
    @person.user_id = @user_id
  	if @person.save
  		redirect_to person_path(@person)
  	else
  		render :new
  	end
  end

  def edit
  	@person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      render :edit
    end
  end

  def search
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end

  private
  	def person_params
  		params.require(:person).permit(:name, :age, :gender, :user_id, :image)
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      @user_id = current_user.id
      person = Person.find_by(user_id: @user_id)
     
      redirect_to person_path(person) #user_path(user.id)#, #:notice => "Logged in!"

    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to new_person_path 
    else
      render "new"
    end
  end

  def show
    @user= User.find(params[:id])
  end

  def destroy
     @user= User.find(params[:id]).destroy
     redirect_to root_path
  end

  private
  # Strong Parameters 
    def user_params
        params.require(:user).permit(:username, :email, :password,
         :password_confirmation)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<%= form_for @address do |f| %>

	<%= f.label :street %>
	<%= f.text_field :street %>

	<%= f.label :city %>
	<%= f.text_field :city %>

	<%= f.label :state %>
	<%= f.text_field :state %>

	<%= f.label :zip %>
	<%= f.text_field :zip %>

	<%= f.hidden_field :person_id, :value => @person.id %>

	<%= f.submit %>

<%end%>

app/views/addresses/edit.html.erb
<h1  class ="home" >Address Edit:</h1>

<div class = "signin">
<%= form_for @address do |f| %>

	<%= f.label :street %>
	<%= f.text_field :street %>

	<%= f.label :city %>
	<%= f.text_field :city %>

	<%= f.label :state %>
	<%= f.text_field :state %>

	<%= f.label :zip %>
	<%= f.text_field :zip %>

	<%= f.submit %>

<%end%>
</div>

app/views/addresses/index.html.erb
<h1>Addresses#index</h1>
<p>Find me in app/views/addresses/index.html.erb</p>

app/views/addresses/new.html.erb
<h1 class ="home">Create new Address</h1>
<hr/>

<%= render(partial: 'form') %>

<%= link_to "person", person_path(@person) %> 

app/views/addresses/show.html.erb
<h1 class ="home" >Address</h1>

<h3 class = "signin">

    <span>Street:</span>
	<span><%= @address.street %></span>
	<br/>

	<span>City:</span>
	<span><%= @address.city %></span>
	<br/>

	<span>State:</span>
	<span><%= @address.state %></span>
	<br/>

	<span>Zip:</span>
	<span><%= @address.zip %></span>
	<br/>
	
</h3>
<%= link_to '<button type="button"> Edit </button>'.html_safe, edit_address_path(@address) %> 
<%= link_to '<button type="button"> Person </button>'.html_safe, person_path(@address.person) %>

app/views/hobbies/_form.html.erb
<%= form_for [@person, @hobby] do |f| %>
  <%= f.label :description %>
  <%= f.text_area :description %> 
  <%= f.submit %>
<% end %>

app/views/hobbies/edit.html.erb
<h1>edit Hobbies</h1>

<%= render(partial: 'form') %>

app/views/hobbies/index.html.erb
<h1>
  <%= @person.name %> 
</h1>
<hr />

<% if @hobbies.any? %>
  <ul>
    <% @hobbies.each do |hobby| %>
      <li>
        <%= link_to hobby.description, person_hobby_path(@person, hobby) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <h3>No hobbies, please add one!</h3>
<% end %>

<hr />
<%= link_to "New", new_person_hobby_path(@person, @hobby) %>
<%= link_to "Back", person_path(@person) %>

app/views/hobbies/new.html.erb
<h1>Hobbies</h1>

<%= render(partial: 'form') %>

app/views/hobbies/show.html.erb
<h1><%= @person.name %></h1>

<h3><span>Hobby:</span>
	<span><%= @hobby.description%></span>
</h3>
<hr/>
<hr/>
<%= link_to "Edit", edit_person_hobby_path(@person, @hobby)%>
<%= link_to "Delete", person_hobby_path(@person, @hobby), method: :delete, data: {confirm: 'Really delete?'} %>
<%= link_to "Person", person_hobbies_path(@person)%>

app/views/homes/index.html.erb
<div class ="home" >
	<h2>Welcome To Paths of love!</h2>
</div>
<div class = "signin">
	<%= link_to '<button type="button"> Sign Up </button>'.html_safe, new_user_path %>
	<%= link_to '<button type="button"> Login </button>'.html_safe, new_session_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash#{name}" %>
    <% end %>
<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for @person, html: { multipart: true } do |f| %>

	<%= f.label :image%>
	<%= f.file_field :image %>
	<%= f.label :name%>
	<%= f.text_field :name %>
	<%= f.label :age %>
	<%= f.text_field :age %>
	<%= f.label :gender %>
	<%= f.text_field :gender %>
	<%= f.hidden_field :user_id, :value => @user%>
	<%= f.submit %>
<%end%>

app/views/people/edit.html.erb
<h1>Edit person:</h1>

<%= form_for @person do |f| %>
	<%= f.label :image%>
	<%= f.file_field :image %>
	<%= f.label :name%>
	<%= f.text_field :name %>
	<%= f.label :age %>
	<%= f.text_field :age %>
	<%= f.label :gender %>
	<%= f.text_field :gender %>
	<%= f.submit %>
<%end%>

app/views/people/index.html.erb
<h1  class ="home" >Meet Hot Singles Near you</h1>

<hr />

<%= form_tag people_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :gender => nil %>
  </p>
<% end %>


<% if @people.any? %>
<ul>
	<%@people.each do |person| %>
	<li>
		<%= link_to person.name, person_path(person) %>
	</li>
	<%end%>
</ul>
<% else %>
<h3>No People, please create one!</h3>
<% end %>

<hr />

<%= link_to '<button type="button"> logout </button>'.html_safe, session_path(@user_id), method: :delete %>

app/views/people/new.html.erb
<h1>Enter new person</h1>

<%= render(partial: 'form') %>

app/views/people/show.html.erb
<div class ="home">
	<%if @person.user_id == @user.id %>
		<h3><%= @person.name %>'s Profile</h3>
	<%else%>
		<h3>More about <%= @person.name %> ...</h3>
	<%end%>
</div>

<h3>
	<span>Age:</span>
	<span><%= @person.age %></span>
	<br/>
	<span>Gender:</span>
	<span><%= @person.gender %></span>
</h3>

<%= image_tag @person.image.url(:medium) %>
<hr/>
<%= link_to '<button type="button"> People </button>'.html_safe, people_path %> |

<%if @person.user_id == @user.id %>
	<%= link_to '<button type="button"> Edit </button>'.html_safe, edit_person_path(@person) %> |

	<%= link_to '<button type="button"> Delete </button>'.html_safe, person_path(@person), method: :delete %> 
	|

	<%if @person.address != nil  %>
		<%= link_to '<button type="button"> Show Address </button>'.html_safe, address_path(@person.address) %>
	<%else%>

		<%= link_to '<button type="button"> Add Address </button>'.html_safe, new_address_path(person_id: @person.id) %>
	<%end%>
	|
<%end%>

<% if @person.hobbies != nil %>
	<%= link_to '<button type="button"> See hobbies 
	</button>'.html_safe, person_hobbies_path(@person) %>
<%end%>  

<%if @person.user_id != @user.id %>
	| 	<%if @person.address != nil  %>
			<%= link_to '<button type="button"> Show Address </button>'.html_safe, address_path(@person.address) %>
		<%end%>
<%end%> |

<%= link_to '<button type="button"> logout </button>'.html_safe, session_path(@person.user_id), method: :delete %>

app/views/users/new.html.erb
<div class = 'home'>
  <h1>Sign Up</h1>
</div>

<div class = 'new_user transbox'>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>
</div>

app/views/users/show.html.erb
<p>show me</p>